### ISSUE TITLE
Create section listing the proxy services enabled for the current user

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/djam#45]
A "Proxy services" section under the "Resources" tab (see #44) will list the proxy services available to the current user.

The logic to retrieve the available services can be taken from [proxy_view](https://github.com/geosolutions-it/djam/blob/main/project/apps/proxy/views.py#L15). It should be extracted and placed into a utils module to be reused by the proxy view and the resources view.

**Functionality**

 - The proxy services enabled for the current user are listed
 - The resource (proxy service) is labelled with its name and rendered as a link to the DJAM service API for the specific resource

**Comment by Gpetrak** [comment]
For the result of this issue please see the following [comment](https://github.com/geosolutions-it/djam/issues/47#issuecomment-2401695348)
